packages:
  - apps/*
  - packages/*

catalogs:
  default:
    '@langchain/google-genai': ^2.1.20
    '@langchain/langgraph': ^1.1.5
    '@types/node': ^25.0.0
    dotenv: ^17.2.3
    cheerio: ^1.2.0
    eslint: ^9.0.0
    mongodb: ^7.1.0
    pino: ^10.3.1
    prettier: ^3.7.4
    tsx: ^4.0.0
    turbo: ^2.7.3
    typescript: ^5.9.3
    zod: ^4.0.0
